version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2-amd64
    container_name: es
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
  data:
    image: ghcr.io/kjvonly/data:v1.0.0
    container_name: data
    volumes:
      - ./data/:/data
  search:
    image: ghcr.io/kjvonly/search:v1.0.0
    container_name: search
    volumes:
      - ./data/:/data
    depends_on:
      - elasticsearch
      - data
    command: ${IPADDR}
  web:
    image: ghcr.io/kjvonly/web:v0.1.1
    container_name: web
    ports:
      - "5000:5000"
    volumes:
      - ./data/:/usr/src/kjvdata
    depends_on:
      - elasticsearch
      - data
  service:
    image: ghcr.io/kjvonly/service:v0.1.1
    container_name: service
    ports:
      - "8080:8080"
    command: /service/bible-api --es-url ${IPADDR}:9200 --arango-db-host ${IPADDR}:49157
    depends_on:
      - arangodb
  arangodb:
    image: arangodb:3.11.2
    container_name: arangodb
    ports:
      - "49157:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=arangodb
  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    ports:
      - "7777:7777"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.conf
      - ./kjvonly.log:/etc/nginx/logs/kjvonly.log
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      IPADDR: ${IPADDR}